[package]
name = "jules-coin"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.10"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
secp256k1 = { version = "0.28", features = ["rand-std"] }
